name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1165

      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn', '**/deps.edn') }}

      - name: Clojure Version
        run: |
          clojure -version
          clojure -M -e '*clojure-version*'
      - name: Dependencies and Prep
        working-directory: service
        run: clojure -T:build:local compile-java
      - name: Compile services
        working-directory: service
        run: clojure -T:build compile-java :aliases '[:local :servlet-api]'
      - name: Execute tests (Clojure 1.11)
        working-directory: tests
        run: clojure -X:test
      - name: Execute tests (Clojure 1.10)
        working-directory: tests
        run: clojure -X:test:1.10
      - name: CVE Vulnerabilities Check
        id: cve-check
        run: clojure -T:build cve-check
      - name: Upload cve-check-results.html
        if: ${{ !cancelled() && steps.cve-check.conclusion }}
        uses: actions/upload-artifact@v3
        with:
          name: cve-check-results.html
          path: target/nvd/dependency-check-report.html
